name: smart_wallet_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Dependências adicionais
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.0+4  # A dependência que você precisa para usar o SQLite
  path: ^1.9.0  # Adicionando a dependência do path

dev_dependencies:
  flutter_test:
    sdk: flutter

  # A lint package para boas práticas
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
